spring:
  profiles:
    active: dev

  datasource:
    name: Blog Meta Data
    url: ${jdbc_url}
    username: ${jdbc_username}
    password: ${jdbc_password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


